### ISSUE TITLE
Git semver is always same as Cargo version

### ISSUE THREAD

**Issue by penberg** [rustyhorde/vergen#100]
With the following `Cargo.toml`:

```
[package]
name = "hello"
version = "1.2.3"
edition = "2021"

[build-dependencies]
anyhow = "1.0"
vergen = { version = "6", default-features = false, features = ["git"] }
```

and the following git tag:

```
% git describe --tags
v0.1.0
```

The `VERGEN_GIT_SEMVER` is always defined as the crate version:

```
% cat build.rs
use anyhow::Result;
use vergen::{Config, vergen};

fn main() -> Result<()> {
    let mut config = Config::default();
    vergen(config)?;
    Ok(())
}
% cat src/main.rs
use std::env;

fn main() {
    println!("{}", env!("VERGEN_GIT_SEMVER"));
}
% cargo run
   Compiling hello v1.2.3 (/Users/penberg/src/hello)
    Finished dev [unoptimized + debuginfo] target(s) in 1.00s
     Running `target/debug/hello`
1.2.3
```

which is unexpected as per documentation:

https://docs.rs/vergen/latest/vergen/#sample-output

The `VERGEN_GIT_SEMVER_LIGHTWEIGHT` variable _does_, however, contain the expected output:

```
% cat build.rs
use anyhow::Result;
use vergen::{Config, vergen, SemverKind};

fn main() -> Result<()> {
    let mut config = Config::default();
    *config.git_mut().semver_kind_mut() = SemverKind::Lightweight;
    vergen(config)?;
    Ok(())
}
% cat src/main.rs
use std::env;

fn main() {
    println!("{}", env!("VERGEN_GIT_SEMVER_LIGHTWEIGHT"));
}
penberg@vonneumann hello % cargo run
   Compiling hello v1.2.3 (/Users/penberg/src/hello)
    Finished dev [unoptimized + debuginfo] target(s) in 1.01s
     Running `target/debug/hello`
v0.1.0
```

**Comment by CraZySacX** [comment]
By default, the "normal" version of the semver will default to the output of libgit2 describe (https://github.com/rustyhorde/vergen/blob/master/src/feature/git.rs#L414-L420).   If you have no tags, or have created only lightweight tags, then describe fails, and semver falls back to the cargo package version.   If this is the case you would need to use the lightweight version.    I can add this distinction to the docs to make it more clear.

**Comment by jasonozias** [comment]
This is default behavior.  Let me know if I need to re-open to discuss.
