### ISSUE TITLE
[offtopic] What is maintainership status of `rl_sys` crate?

### ISSUE THREAD

**Issue by vi** [rustyhorde/vergen#108]
crates.io repository link points to a [nonexistent repository](https://github.com/rustyhorde/readline-sys.git) in this `rustyhorde` namespace.
It cannot be build with modern Rust (one `unsafe` is missing), but after fixing the issue it seems to work.
Shall a fork be published to crates.io, shall original `rl_sys` crate be re-pointed to some new repository or shall the Git repository (possible archived) be restored at original location?

**Comment by jasonozias** [comment]
`rs_sys` is unmaintained.   There are better crates out there (`rustyline` for example) that are maintained and do a much better job.    I would recommend switching.    If you really need to use `rl_sys` I could re-publish the project, although it wouldn't be maintained.
