### ISSUE TITLE
SemverKind::Lightweight changes the environment variable

### ISSUE THREAD

**Issue by koivunej** [rustyhorde/vergen#111]
One of the mistakes I always do when enabling `vergen` (and soon after forgetting about it) is to jump through hoops first discovering the need for `SemverKind::Lightweight` through #100 (or just trial and error), then I need to look up the environment keys as the `env!("VERGEN_GIT_SEMVER")` no longer works, find out I need to use `env!("VERGEN_GIT_SEMVER_LIGHTWEIGHT")`.

While looking around, I noticed that the landing page of docs lists an interesting example value for the lightweight version:

https://github.com/rustyhorde/vergen/blob/d82785850ce563c24f5a157992a7d3e59726078a/src/lib.rs#L112-L113

Further digging this, the old commit no longer exists, but similar commit 61e560eacc2622c268660e83275d6ee3b4e70107 does. For it, git 2.25.1 reports `5.0.1-2-g61e560e` for both `git describe` with and without `--tags`.

It seems that it would had helped me use vergen if:

- the VERGEN_GIT_SEMVER name would always stay the same (regardless of lightweight or not)
- by default, the `--tags` query could probably be made -- I cannot see any downsides, but there of course could be
- the error from `git describe` operation shouldn't be hidden, instead a hint to disable that variable could be displayed if the branch had no tags

**Comment by CraZySacX** [comment]
This should be resolved with the release of [`8.0.0-beta.0`](https://crates.io/crates/vergen/8.0.0-beta.0).   VERGEN_GIT_SEMVER has been renamed to VERGEN_GIT_DESCRIBE as that more accurately represents what is being generated now.   I plan to back port some of the new features back to version 7 and 6 over the next month.  Feel free to re-open if you are still having issues.
