### ISSUE TITLE
Compile Error on vergen-7.1.0

### ISSUE THREAD

**Issue by fishseabowl** [rustyhorde/vergen#117]
I get the following error when compiling vergen-7.1.0. Please let me know if you need more details.

error[E0308]: mismatched types
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/vergen-7.1.0/src/feature/si.rs:265:20
    |
265 |     *user.uid() == process.uid
    |                    ^^^^^^^^^^^ expected `u32`, found enum `Option`
    |
    = note: expected type `u32`
               found enum `Option<u32>`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `vergen` due to previous error

**Comment by CraZySacX** [comment]
I had to pin the `sysinfo` version as breaking changes were made.   There are newer versions of `vergen` that shouldn't exhibit this compile error.    If you can upgrade to those, that would be idea.  I may pull some of this older versions if this continues to be an issue.

**Comment by CraZySacX** [comment]
Feel free to re-open this is you haven't found a suitable solution.
