### ISSUE TITLE
Version 2.1 backport is incomplete

### ISSUE THREAD

**Issue by RalfJung** [rustyhorde/vergen#12]
The master README says about Version 2.1

> Backport of the 3.x.x changes to work on stable until Rust 2018 hits stable.

So I just tried to use `generate_cargo_keys`, but that does not seem to exist on that branch.

**Comment by CraZySacX** [comment]
It was a backport of the 3.x changes into the 2.0 API, so that method won't exist.

**Comment by RalfJung** [comment]
Okay. The README sounds to me like the API is also backported (it's part of the "changes" sine it got, well, changed). Might be worth clarifying.

**Comment by CraZySacX** [comment]
Sure, I can clarify.
