### ISSUE TITLE
Advice on implementing long version command

### ISSUE THREAD

**Issue by mickvangelderen** [rustyhorde/vergen#123]
I'm using vergen in a number of applications. Ideally I would like to configure all of the build information in `build.rs` through the vergen `Config` and then spit out a formatted text table.

Is there some code already written that I can use to do that or do I have to make one myself? I do not want to reimplement the same thing in every CLI tool I build.

**Comment by CraZySacX** [comment]
I can add this feature into version 8.   This would be useful in my projects that use `vergen` as well.

**Comment by CraZySacX** [comment]
Released an initial pretty printer as the  [`vergen-pretty`](https://crates.io/crates/vergen-pretty) crate.   Documentation at [`docs.rs`](https://docs.rs/vergen-pretty/latest/vergen_pretty/).  This met my needs but feel free suggest improvements.
