### ISSUE TITLE
Handle VERGEN_GIT_* more gracefully if the source is not a git repo

### ISSUE THREAD

**Issue by puzzlewolf** [rustyhorde/vergen#124]
Thanks for making `vergen` :+1: 

Followup of #101.

It's quite common for Linux distrubutions to build a package from a source tarball, and not the git repo of the package. In that situation, if the `"git"` feature is present, the `vergen(Config::default())` function in `build.rs` will Error, and no `VERGEN_*` variables will be set. Sadly, that also includes vergen variables from other features, like `VERGEN_BUILD_*` or `VERGEN_RUSTC_*`, which do not depend on git.

In #101, ignoring the Error `vergen()` returns and using `option_env!` later seems to have been okay, probably because the user was only interested in `VERGEN_GIT_*`. However, ignoring Errors does not feel nice :)

I can think of two ways around this:
- @rapiz1's suggestion: instead of failing completely, simply don't set corresponding Git env vars. 
- Or, provide a configuration option "allow-nonexistent" (name TBD) for the `Git` struct, to keep the old behavior but allow the new.

I'm not sure which I'd prefer, but I'm happy to implement whatever is decided :)

**Comment by CraZySacX** [comment]
I like the idea of a configuration option, basically turning it on would skip errors and leave the env vars unset.   I think we should add that to all of the various vergen features as it might be useful outside of just the git feature.   We will have to document that `option_env` should be used when enabling this config opt as the env vars might not be set.
