### ISSUE TITLE
New version with fix

### ISSUE THREAD

**Issue by patrickelectric** [rustyhorde/vergen#135]
After landing 6a2e7545feae37fab052dfe8d5d086827c0d70ab, a new version should be created to allow the usage of the latest features without compilation error

**Comment by CraZySacX** [comment]
Working on it now.   Waiting for pipelines to finish out.

**Comment by CraZySacX** [comment]
`7.4.1` has been released.

**Comment by patrickelectric** [comment]
Thanks @CraZySacX!
