### ISSUE TITLE
Allow to read variables values during build

### ISSUE THREAD

**Issue by ventaquil** [rustyhorde/vergen#138]
Currently I have simple `build.rs` file which is setting `--cfg {CHANNEL}` like `--cfg nightly`.

I have few checks in my code like `#[cfg_attr(nightly, ...)]` to compile some parts of code only for nightly builds.

It would be perfect to allow be able to read some values from vergen.

```rust
fn main() -> Result<()> {
    let config = Config::default();
    let rustc_channel = ...; // do some magic here
    println!("cargo:rustc-cfg={rustc_channel}");
    // or
    println!("cargo:rustc-cfg=channel=\"{rustc_channel}\"");
    vergen(config)?;
}
```

**Comment by CraZySacX** [comment]
I think the [`rustc_version`](https://crates.io/crates/rustc_version) crate would allow you to do that.   Closing this as I think that's what you are looking for.   If not, feel free to re-open this ticket with a few more details about what specifically you are trying to read.
