### ISSUE TITLE
Read environment variables to remove impurities

### ISSUE THREAD

**Issue by psionic-k** [rustyhorde/vergen#141]
It's a bit early.  I'm supporting a library for building crates that sometimes use vergen.

I need to know the environment options to disable all impurity in the vergen crate and then also to inject pure information like source git SHA and linking information.

While #140 is what brought us here, let me explain why all of this behavior is critical.

https://docs.rs/vergen/latest/vergen/

The sysinfo is not reproducible across builds.  Options like CPU identifiers are injecting system impurity directly into the results.  What I'm saying is that Nix users will _never_ choose to put this information into the results because it creates non-reproducible builds, meaning all the tooling for detecting impurity will be set off.  

While the crate seems like a small utility that can be included without much effect on consumers, just like Debian CI, the Nix build system also will not include the `.git` directory in the source.  We can hack in the creation of a git directory, but the system information needs a better solution.  Even if it requires using hardcoded fallback values such as "pure-evaluation-build-generic-cpu-id" etc, that's preferable to allowing any builder impurity into outputs.

When a user wants to build a crate that depends on vergen, they need to be able to force the impurity out even if the crate's build.rs is requesting the impurity.  If this is done via an environment variable, I can easily include it as an override for all vergen users.  I will already need such an override due to the old versions that will still need support for missing `.git`

https://github.com/cargo2nix/cargo2nix/issues/307

**Comment by CraZySacX** [comment]
The basics of this request is the ability to force a reproducible build regardless of the configuration requested.  I can take a stab at forcing sane defaults, but may need some input in that area.   As this is the 2nd request to have the ability to build without a `.git` directory I'll make sure that is available as well.

**Comment by CraZySacX** [comment]
#146 should address this issue.  Feel free to comment on that PR if you feel I've missed anything.   I may back port some of the new features to older versions as well.

**Comment by CraZySacX** [comment]
This should be resolved with the release of [`8.0.0-beta.0`](https://crates.io/crates/vergen/8.0.0-beta.0).   I also plan to back port the relevant fixes to version 7 and 6 over the next month as well.
