### ISSUE TITLE
CVE on git2

### ISSUE THREAD

**Issue by irevoire** [rustyhorde/vergen#158]
Hello, there has been a CVE on your git2 dependency.
It was fixed in the `v0.16.1`.
Do you think it's doable to update the dependency in vergen and make a new release?

**Comment by CraZySacX** [comment]
Yep, I'll get that out shortly.

**Comment by CraZySacX** [comment]
7.5.1 has been released.  Closing.

**Comment by irevoire** [comment]
That was fast! Thanks a lot ❤️
