### ISSUE TITLE
Are Vergen releases following semantic versioning?

### ISSUE THREAD

**Issue by joaoantoniocardoso** [rustyhorde/vergen#170]
Hello!

I'm quite confused. Are Vergen releases following semantic versioning? Reading the [v8.0.0 release message](https://github.com/rustyhorde/vergen/releases/tag/8.0.0) it says that only `gix` and `readme` were updated. Is this breaking anything in the API for the users?

I'm asking because while I like to keep using the most updated version of the libraries, I want to understand what's changing and what could affect my side.

Thanks

**Comment by jasonozias** [comment]
Yes it does.   There were 11 beta release of 8 before the release was cut.   I should have mentioned that in the release notes.   I'm going to look into automated change logs as well.
