### ISSUE TITLE
Missing VERGEN_BUILD_SEMVER and VERGEN_CARGO_PROFILE in vergen 8

### ISSUE THREAD

**Issue by alcroito** [rustyhorde/vergen#171]
Hi,

Upgrading from 7 to 8 shows the following errors in my project, after adapting the builder to output everything:

```
error: environment variable `VERGEN_BUILD_SEMVER` not defined
   |
   |         env!("VERGEN_BUILD_SEMVER"),
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: environment variable `VERGEN_CARGO_PROFILE` not defined
   |
   |         env!("VERGEN_CARGO_PROFILE"),
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
`VERGEN_GIT_SEMVER_LIGHTWEIGHT` is also missing

Are these env vars intentionally removed?

**Comment by CraZySacX** [comment]
* `VERGEN_BUILD_SEMVER` was removed in lieu of either using `CARGO_PKG_VERSION` (supplied by cargo) or `VERGEN_GIT_DESCRIBE`.   This was renamed to better reflect what is actually being generated for consumption.  `VERGEN_GIT_DESCRIBE` can be configured in a manner to display the same information that `VERGEN_GIT_SEMVER_LIGHTWEIGHT` used to.  Docs are at https://docs.rs/vergen/latest/vergen/struct.EmitBuilder.html#method.git_describe (specifically configured with `--tags`).
* `VERGEN_CARGO_PROFILE` was removed in lieu of `VERGEN_CARGO_OPT_LEVEL`.   This was done per the recommendation in the [cargo documentation](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts) to use `OPT_LEVEL` over `PROFILE`.   They recommend no longer using the `PROFILE` variable set by cargo at build time.
