### ISSUE TITLE
VERGEN_CARGO_PROFILE missing in 8.0

### ISSUE THREAD

**Issue by crumblingstatue** [rustyhorde/vergen#179]
Is this intentional? There doesn't seem to be an option for it anymore.

**Comment by CraZySacX** [comment]
Yes, see the [comment](https://github.com/rustyhorde/vergen/issues/171#issuecomment-1483818326) here.   The tldr is the cargo maintainers don't recommend using the `PROFILE` variable anymore.  `OPT_LEVEL` is a better representation of what `cargo` is applying.

**Comment by crumblingstatue** [comment]
Thank you for the information!
