### ISSUE TITLE
Add `emit_and_set()` function to both emit the `cargo:rustc-env=...` and set the environment variables

### ISSUE THREAD

**Issue by tgross35** [rustyhorde/vergen#188]
I have a case where I'd like to be able to use the same versions and timestamp elsewhere in `build.rs`. Is there any way currently to also write the environment variables, instead of just emitting for cargo?

If not, a `emit_and_set()` function that does this would be helpful.

**Comment by CraZySacX** [comment]
There is not a way to do this currently.  I will take a look at adding this over this next weekend.
