### ISSUE TITLE
Update git2 to 0.17.1

### ISSUE THREAD

**Issue by Thorongil80** [rustyhorde/vergen#194]
Hi,

I use git2 in my project for other purposes than vergen's needs. There is a vulnerability in 0.16.1, I want to update to 0.17.1.

vergen = { version = "8.1.1", features = ["build", "cargo", "git", "git2"] }
git2 = "0.17.1"

But this gives me:

error: failed to select a version for `libgit2-sys`.
    ... required by package `git2 v0.16.1`
    ... which satisfies dependency `git2-rs = "^0.16.1"` of package `vergen v8.1.1`
    ... which satisfies dependency `vergen = "^8.1.1"` of package `pipecon v0.1.0 (/sapmnt/HOME/d041727/IdeaProjects/pipecon)`
versions that meet the requirements `^0.14.2` are: 0.14.2+1.5.1
the package `libgit2-sys` links to the native library `git2`, but it conflicts with a previous package which links to `git2` as well:
package `libgit2-sys v0.15.1+1.6.4`
    ... which satisfies dependency `libgit2-sys = "^0.15.1"` of package `git2 v0.17.1`
    ... which satisfies dependency `git2 = "^0.17.1"` of package `pipecon v0.1.0 (/sapmnt/HOME/d041727/IdeaProjects/pipecon)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the links ='libgit2-sys' value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.
failed to select a version for `libgit2-sys` which could resolve this conflict
Process finished with exit code 101

Kindly switch to 0.17.1 :-)

Thanks,
Thomas

**Comment by CraZySacX** [comment]
I've already updated on master.  I'll get a release out today.
