### ISSUE TITLE
Support `cargo:rustc-env`

### ISSUE THREAD

**Issue by kennytm** [rustyhorde/vergen#2]
Starting from [Rust 1.19 (cargo 0.20.0)](https://github.com/rust-lang/cargo/issues/3929) (next beta), one may use

```rust
println!("cargo:rustc-env=ENVVAR=value");
```

in the `build.rs` to define a variable for rustc, allowing code to use 

```rust
env!("ENVVAR")
```

`vergen` could be extended to support this, so user could read the variables without including OUT_DIR.

**Comment by CraZySacX** [comment]
Version 2.0.0 now supports passing of build information for use with the `env!` macro.  Closing.
