### ISSUE TITLE
Most BUILD and GIT vergen variables just hold "VERGEN_IDEMPOTENT_OUTPUT"

### ISSUE THREAD

**Issue by jkbecker** [rustyhorde/vergen#216]
Hello,

I built a crate which gets built with the following build.rs file:

```rust
use std::error::Error;

use vergen::EmitBuilder;

fn main() -> Result<(), Box<dyn Error>> {
    // Emit the instructions
    EmitBuilder::builder()
        .all_build()
        .all_cargo()
        .all_git()
        .all_rustc()
        .emit()?;
    Ok(())
}
```

Just discovered that using that crate in another application does not, as expected, give me build information, but instead fills out every `VERGEN_BUILD_*` and `VERGEN_GIT_*` variables with "VERGEN_IDEMPOTENT_OUTPUT", but does properly populate `VERGEN_RUSTC_*` and `VERGEN_CARGO_*` variables.

To give a specific example, I have this struct:
```rust
#[derive(Debug, PartialEq, Deserialize, Serialize)]
pub struct BuildInfo {
    build_timestamp: String,
    build_date: String,
    git_branch: String,
    git_timestamp: String,
    git_date: String,
    git_hash: String,
    git_describe: String,
    rustc_host_triple: String,
    rustc_version: String,
    cargo_target_triple: String,
}

impl BuildInfo {
    fn new() -> BuildInfo {
        BuildInfo {
            build_timestamp: String::from(env!("VERGEN_BUILD_TIMESTAMP")),
            build_date: String::from(env!("VERGEN_BUILD_DATE")),
            git_branch: String::from(env!("VERGEN_GIT_BRANCH")),
            git_timestamp: String::from(env!("VERGEN_GIT_COMMIT_TIMESTAMP")),
            git_date: String::from(env!("VERGEN_GIT_COMMIT_DATE")),
            git_hash: String::from(env!("VERGEN_GIT_SHA")),
            git_describe: String::from(env!("VERGEN_GIT_DESCRIBE")),
            rustc_host_triple: String::from(env!("VERGEN_RUSTC_HOST_TRIPLE")),
            rustc_version: String::from(env!("VERGEN_RUSTC_SEMVER")),
            cargo_target_triple: String::from(env!("VERGEN_CARGO_TARGET_TRIPLE")),
        }
    }
}
```
and creating one and debug-printing it looks like this:
```
BuildInfo {
    build_timestamp: "2023-06-09T15:54:46.775171000Z",
    build_date: "2023-06-09",
    git_branch: "VERGEN_IDEMPOTENT_OUTPUT",
    git_timestamp: "VERGEN_IDEMPOTENT_OUTPUT",
    git_date: "VERGEN_IDEMPOTENT_OUTPUT",
    git_hash: "VERGEN_IDEMPOTENT_OUTPUT",
    git_describe: "VERGEN_IDEMPOTENT_OUTPUT",
    rustc_host_triple: "aarch64-apple-darwin",
    rustc_version: "1.69.0-beta.1",
    cargo_target_triple: "aarch64-apple-darwin",
}
```

Any pointers as to why this could be happening are much appreciated!

**Comment by CraZySacX** [comment]
With version 8, the default switched from erroring on failure, to always running (and setting defaults) on errors.  One reason for the output you are seeing could be a missing `.git` directory, or no commits yet.

You can re-enable the error behavior with [`fail_on_error`](https://docs.rs/vergen/latest/vergen/struct.EmitBuilder.html#method.fail_on_error) on the builder.   The output from the error might give you more clues to the root issue.

**Comment by jkbecker** [comment]
Thanks, that was helpful for troubleshooting. Now I know what the problem is, but not, how to solve it:
- the `vergen` data is defined and populated in a library crate which I publish to crates.io
- the actual application uses that library crate as a dependency
- while both of these projects are in proper git repositories, the fact that the library crate is pulled in via `cargo` means that *that* version of the code probably is not (its own) git repo?

What I was trying to get here is to establish what git hash/date the *library* crate was built with; in other words, that may have to be something I bake into the `cargo publish` process, vs the build process of the application. I assume `vergen` is not the right tool for that, or is there a way to achieve this?

**Comment by jkbecker** [comment]
I did actually try to add a `build.rs` to the application project, hoping that it would run after the build of the library (because the library is a dependency) and therefore overwrite the failed variables... this still doesn't work though, as it will pick up build information from the application project, not the library.

I guess I'll close this here, as I also don't really know how to address this with `vergen` based on what I've learned... Appreciate the help!
