### ISSUE TITLE
Document all available variables

### ISSUE THREAD

**Issue by ctron** [rustyhorde/vergen#220]
Maybe I am missing something obvious, but I couldn't easily find an list of variables which are available.

**Comment by jasonozias** [comment]
There are some on the docs.rs (https://docs.rs/vergen/latest/vergen/index.html#environment-variables)
Also here is the complete list (https://docs.rs/vergen/latest/vergen/struct.EmitBuilder.html#method.emit).

I agree this could be more prominent though.  I'll likely move the emit docs up to the README.md and higher up in the main page of the docs.

**Comment by ctron** [comment]
Ah, I didn't find those. Thanks for pointing me to them.

> I agree this could be more prominent though. I'll likely move the emit docs up to the README.md and higher up in the main page of the docs.

That would be awesome!

**Comment by CraZySacX** [comment]
Will be working on docs update to bring some more details up to the top level.   Closing this as the main issue was resolved.
