### ISSUE TITLE
Vergen doesn't respect configured location for `build.rs`

### ISSUE THREAD

**Issue by alexrudy** [rustyhorde/vergen#222]
I notice that even when I set `build = ...something` in my `Cargo.toml`, vergen still produces a rerun-if-changed directive pointing to `build.rs` in the crate root directory. It would be nice if vergen would respect the current crate's configuration.

(See https://github.com/rustyhorde/vergen/blob/master/vergen/src/emitter.rs#L285)

**Comment by jasonozias** [comment]
Agree.  Didn't know that configuration existed.

**Comment by jasonozias** [comment]
So digging into this some, Cargo does not export the build script information via [enviroment variables](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts).  That means I can't detect a non-standard build script path automatically.   I can add the option to configure that path however.
