### ISSUE TITLE
Add VERGEN_GIT_DIRTY

### ISSUE THREAD

**Issue by bouk** [rustyhorde/vergen#237]
Should have the value 'true' or 'false' depending on whether the git tree was dirty

**Comment by kwinz** [comment]
I just had the same need. I programmed this myself:

```
    let has_uncommited_uncached_changes = Command::new("git")
        .args(&["diff", "--quiet"])
        .status()
        .unwrap()
        .code()
        .unwrap()
        != 0;

    let has_uncommited_cached_changes = Command::new("git")
        .args(&["diff", "--cached", "--quiet"])
        .status()
        .unwrap()
        .code()
        .unwrap()
        != 0;

    println!(
        "cargo:rustc-env=GIT_DIRTY={}",
        if has_uncommited_uncached_changes || has_uncommited_cached_changes {
            "uncommited-changes"
        } else {
            "clean"
        }
    );
```

I called it "uncommited-changes" instead of "clean" because I also wanted to include changes that are staged but not commited yet.

**Comment by hgomersall** [comment]
I've just submitted a merge request to address this in #281 .

**Comment by CraZySacX** [comment]
This has been added as of release 8.2.7 for the `git2` and `gitcl` feature.   `gix` support will be added when `gix-status` implementation is more complete.
