### ISSUE TITLE
Feature request: add new environment variable that indicates working directory clean or dirty

### ISSUE THREAD

**Issue by kwinz** [rustyhorde/vergen#257]
Hi!

It makes a significant difference if I check out a particular commit hash and then directly build.
Or if I check out a hash, make changes without commiting and then build from a dirty directory.
But both builds give the same `VERGEN_GIT_SHA`.

This happens a lot during development when it's not built from CI. And I don't want executables to get mixed up. The build time would probably be different, but that's too noisy and not the same conceptually as the source file state. Therefore I want to make the dirty status part of the build version.

There are multiple ways to check if the working directory is clean:
https://remarkablemark.org/blog/2017/10/12/check-git-dirty/

Either use the output of gitcli  `git diff --stat` or `git status --short`.
But the easiest is probably to check whether  `git diff --quiet` has an exit code !=0

`git diff --quiet && git diff --cached --quiet && echo 'clean'` prints "clean" only if the working directory is clean.

The return value could be used for new environment variable `VERGEN_GIT_DIRTY` that either contains a boolean or `dirty` or `clean`. Either would be fine.

Not sure yet how to tell cargo to rebuild the env `VERGEN_GIT_DIRTY` on any file change.

Would it be ok if I sent a pull request for `VERGEN_GIT_DIRTY`?

**Comment by kwinz** [comment]
Seems to be a duplicate of #237

**Comment by CraZySacX** [comment]
Yep, it's a duplicate.  If you'd like to give a PR a shot that would be wonderful.  I've been super busy the past few months and haven't had any time to spend on this project.   I'll have some time later this month if you can't get to it.

**Comment by CraZySacX** [comment]
Closing.  Will complete this feature request with #237
