### ISSUE TITLE
Insufficient escaping in code generator

### ISSUE THREAD

**Issue by kornelski** [rustyhorde/vergen#26]
Code generator doesn't escape strings:

https://github.com/rustyhorde/vergen/blob/master/src/output/codegen.rs#L23

Adding quotes around the value is not sufficient - the value could contain quotes or end with backslash, and cause the value to become arbitrary Rust source code.

With the current set of inputs I don't think it's a real vulnerability, but it does increase risk of creating one if some more arbitrary build info was added in the future.

**Comment by teor2345** [comment]
Rather than trying to escape string terminators and backslashes, it would be more reliable to just delete those characters.
