### ISSUE TITLE
Remove git2 dependency

### ISSUE THREAD

**Issue by odyslam** [rustyhorde/vergen#261]
I can't seem to be able to remove the dependency on `git2`, even if I am not using the feature.

**Comment by CraZySacX** [comment]
Going to need more information.   Assuming the config you have setup is the same as your other issue, I'm showing the `cargo tree` output shown below (no git2 dependency).
![vergen-cl-tree](https://github.com/rustyhorde/vergen/assets/1423378/3db3c419-071d-460e-bb2a-d8cd8479e9b7)

**Comment by odyslam** [comment]
This was due to a dependecy using vergen, but with git2.
