### ISSUE TITLE
Consistency between the documentation and the outputs

### ISSUE THREAD

**Issue by jreniel** [rustyhorde/vergen#262]
When I do:
`println!("git describe: {}", env!("VERGEN_GIT_DESCRIBE"));`
I just get:
`git describe: 45e8eb8`

But I actually wanted to
`"git_describe": "0.0.0-7-gc96c096",`
Which is how it is described in the docs.
That is, I was expecting it to prepend the semantic version to the hash.
How can I achieve this?
Also, I definitely upvote https://github.com/rustyhorde/vergen/issues/237 so that we would get something more similar to: `0.0.0-7-gc96c096-dirty`

**Comment by CraZySacX** [comment]
What git feature do you have configured (gitcl, gitoxide or git2)?
gitcl runs `git describe --always` ([here](https://github.com/rustyhorde/vergen/blob/master/vergen/src/feature/git/cmd.rs#L105-L109))
git2 runs the code [here](https://github.com/rustyhorde/vergen/blob/master/vergen/src/feature/git/git2.rs#L419-L445)
gitoxide run the code [here](https://github.com/rustyhorde/vergen/blob/master/vergen/src/feature/git/gix.rs#L411-L433) 

They all support the dirty flag via the [`git_describe`](https://docs.rs/vergen/8.2.0/vergen/struct.EmitBuilder.html#method.git_describe)  configuration function

**Comment by CraZySacX** [comment]
Closing as this particular dirty output is currently supported.  Will also be adding a `VERGEN_GIT_DIRTY` variable as requested in #237 .  Feel free to re-open if these don't satisfy your request.

**Comment by jreniel** [comment]
Thanks, @CraZySacX, I was about to reply, as I'm just starting my day. I don't need to reopen, but I'm not exactly clear how to configure through the EmitBuilder. It would be nice to have some updated examples.
All in all I want to thank you for your hard work with this crate and for keeping it accessible for the community.

**Comment by CraZySacX** [comment]
Here is how it's configured, sample output below as well:

```
use anyhow::Result;
use vergen::EmitBuilder;

pub fn main() -> Result<()> {
    EmitBuilder::builder()
        .all_git()
        .git_describe(true, true, None)
        .emit()
}
```

```
Describe (    git): 0.1.0-1-gcfece0a
```

**Comment by jreniel** [comment]
Thanks for your help! =) =) =)
