### ISSUE TITLE
Goal of vergen is unclear from the readme.

### ISSUE THREAD

**Issue by gl-yziquel** [rustyhorde/vergen#350]
Hi.

I've been trying to build redox from source, and it failed when trying to compile cosmic-files, which uses vergen.

https://github.com/pop-os/cosmic-files/issues/250

I ended up here trying to debug that build. Unfortunately, the readme file is not written with someone like me in mind, who tries to get into a build system from the outside. It is pretty unclear what vergen does, and the readme file does seem to assume a pretty big deal of implicit knowledge when it comes to the way vergen is to be used and the use case it is trying to solve.

Please add one or two paragraphs in the readme clarifying the rôle of this crate.

**Comment by CraZySacX** [comment]
That's a good point.  Just so it's documented here (I will also update the README), `vergen` and the associated other tools allow you to embed environment variables determined at build time into your code with the [env!](https://doc.rust-lang.org/std/macro.env.html) or [option_env!](https://doc.rust-lang.org/std/macro.option_env.html) macros.   The vast majority of my use is to include git related data into the projects I build.

**Comment by CraZySacX** [comment]
Additionally, you may be interested about the mechanics.  This is found in the [Build Scripts](https://doc.rust-lang.org/cargo/reference/build-scripts.html) section of the cargo documentation.

**Comment by gl-yziquel** [comment]
@CraZySacX thank you for taking that remark constructively.
