### ISSUE TITLE
Publish new version of vergen-gix on crates.io

### ISSUE THREAD

**Issue by danielhaap83** [rustyhorde/vergen#351]
Can you publish a new version of vergen-gix on crates.io to fix the security issues from gix version < 0.63.0, please.

Would be very helpful.

Thanks and BR.

**Comment by CraZySacX** [comment]
Sure good call.  I'll get that out later today.

**Comment by CraZySacX** [comment]
Sorry got busy and forgot to do this.  I've released version 1.0.0 of `vergen-gix`.

**Comment by danielhaap83** [comment]
Thank you!
