### ISSUE TITLE
Cross-compilation fails due to transitive `openssl-sys` dependency

### ISSUE THREAD

**Issue by Turbo87** [rustyhorde/vergen#36]
v4.0 switched to using `git2` instead of running `git` commands, but unfortunately `git2` has a transitive dependency on `openssl-sys`, which makes it hard to use when cross-compiling for e.g. a Raspberry Pi via https://github.com/rust-embedded/cross.

**Comment by CraZySacX** [comment]
Try pulling in `vergen` with
```
vergen = { version = "4', default-features = false, features = ["build", "rustc"] }
```

This should allow you to build without pulling in `openssl-sys`.
