### ISSUE TITLE
Change `COMMIT_DATE` constant

### ISSUE THREAD

**Issue by Silverhorn27** [rustyhorde/vergen#50]
`COMMIT_DATE` is so awful, will be cool have something like this but with separated time and need to use UTC time.
For example, instead of this need the follow:
 - `COMMIT_DATE` = 2021-02-11
 - `COMMIT_TIME_UTC` = 15:05:53

**Comment by CraZySacX** [comment]
I think I'm going to change the timestamp handling to allow for both a timestamp version and the version you recommend with the date and time split.   I'd also like to be able to allow for UTC vs. Local for both.  Right now the build timestamp is UTC only, and the git commit timestamp is the timezone where the user committed from (per git2).

VERGEN_BUILD_DATE
VERGEN_BUILD_TIME
VERGEN_BUILD_TIMESTAMP
VERGEN_GIT_COMMIT_DATE
VERGEN_GIT_COMMIT_TIME
VERGEN_GIT_COMMIT_TIMESTAMP

And you could specify UTC or Local.

**Comment by CraZySacX** [comment]
Closed with #52.
