### ISSUE TITLE
Please add support for git tag

### ISSUE THREAD

**Issue by imp** [rustyhorde/vergen#71]
Perhaps something like `VERGEN_GIT_TAG` in case the current commit has a git tag? And then `option_env!` in the code will handle the case when there is no tag.

**Comment by jasonozias** [comment]
The `VERGEN_GIT_SEMVER`  output already can do this.   By default, it uses the `describe` functionality of `git2`, which will find the most recent annotated tag from the current commit (see https://git-scm.com/docs/git-describe).   Now if there are no tags, or no reachable tags, then currently `VERGEN_GIT_SEMVER` will fall back to using the `CARGO_PKG_VERSION` environment variable set by cargo.

I think that would be sufficient.   I suppose we could make the fallback optional, and not have this variable set.   Let me know if that is the case.

**Comment by jasonozias** [comment]
Closing as there is a workable solution.   Feel free to re-open if you don't agree.
