### ISSUE TITLE
Build error in version `5.1.12` 

### ISSUE THREAD

**Issue by kahlil29** [rustyhorde/vergen#82]
I think I have a dependency on `vergen` in my project. I use it to embed the git sha_256 (hash) into the code so that I can easily check the commit version/info after the project is deployed.

The errors I get are (via my CI build running Ubuntu 18.04 LTS) : 

```
error[E0658]: the `unsafe_op_in_unsafe_fn` lint is unstable
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/vergen-5.1.12/src/lib.rs:184:1
    |
184 | / #![deny(
185 | |     absolute_paths_not_starting_with_crate,
186 | |     anonymous_parameters,
187 | |     array_into_iter,
...   |
291 | |     while_true
292 | | )]
    | |__^
    |
    = note: see issue #71668 <https://github.com/rust-lang/rust/issues/71668> for more information

error[E0710]: an unknown tool name found in scoped lint: `rustdoc::bare_urls`
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/vergen-5.1.12/src/lib.rs:307:5
    |
307 |     rustdoc::bare_urls,
    |     ^^^^^^^

error[E0710]: an unknown tool name found in scoped lint: `rustdoc::broken_intra_doc_links`
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/vergen-5.1.12/src/lib.rs:308:5
    |
308 |     rustdoc::broken_intra_doc_links,
    |     ^^^^^^^

error[E0710]: an unknown tool name found in scoped lint: `rustdoc::invalid_codeblock_attributes`
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/vergen-5.1.12/src/lib.rs:309:5
    |
309 |     rustdoc::invalid_codeblock_attributes,
    |     ^^^^^^^

error[E0710]: an unknown tool name found in scoped lint: `rustdoc::invalid_html_tags`
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/vergen-5.1.12/src/lib.rs:310:5
    |
310 |     rustdoc::invalid_html_tags,
    |     ^^^^^^^

error[E0710]: an unknown tool name found in scoped lint: `rustdoc::missing_crate_level_docs`
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/vergen-5.1.12/src/lib.rs:311:5
    |
311 |     rustdoc::missing_crate_level_docs,
    |     ^^^^^^^

error[E0710]: an unknown tool name found in scoped lint: `rustdoc::missing_doc_code_examples`
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/vergen-5.1.12/src/lib.rs:312:5
    |
312 |     rustdoc::missing_doc_code_examples,
    |     ^^^^^^^

error[E0710]: an unknown tool name found in scoped lint: `rustdoc::private_intra_doc_links`
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/vergen-5.1.12/src/lib.rs:314:5
    |
314 |     rustdoc::private_intra_doc_links,
    |     ^^^^^^^

error: aborting due to 8 previous errors

Some errors have detailed explanations: E0658, E0710.
For more information about an error, try `rustc --explain E0658`.
error: could not compile `vergen`
``` 

I tried cloning this repository and compiling the latest `master` via `cargo build --release` and I get a lot of warnings and also the same error(s) on my local machine (Macos Catalina).

**Comment by jasonozias** [comment]
Hmm that interesting.   You appear to be getting errors about the rustdoc lints which were added in 1.52.0.   Are you by chance using an older stable version?

If so I will add support to check for older stable versions and configure the lints appropriately.

**Comment by kahlil29** [comment]
Ah, thanks for spotting that. I'm not very well-versed with the Rust compiler versioning and dependency mgmt stuff. 
On my local system, I have the following:  

```
rustc --version
rustc 1.47.0
``` 

CI is probably similar. I have no issues upgrading to the latest stable, I doubt it would break anything, I'll try that. 
Thanks a lot for pointing that out for me 👍🏻

**Comment by jasonozias** [comment]
I've also pushed out `5.1.13` where the lints are disabled if you are using a version of rust older than the MSRV (1.53 currently).   The lints are only really needed for development so this should be safe.

**Comment by jasonozias** [comment]
Going to close this as fixed with the latest release.  Feel free to re-open if that's not the case for you.

**Comment by kahlil29** [comment]
Amazing! I've modified my CI base docker image to use the current MSRV and I've also tested this locally on my system with the older `rustc` version (1.47.0) and both compile successfully! 

Thanks for : 
- Such prompt & helpful responses to my question/issue
- Insanely quick action and release of a new version that solves the issue 

It's great to depend on libraries maintained by people like you & you are part of what makes the Rust community awesome 🎉  🥇
