### ISSUE TITLE
vergen fails to build on NetBSD

### ISSUE THREAD

**Issue by grtcdr** [rustyhorde/vergen#89]
Is support for BSDs planned? A crate I maintain has just started using vergen to help debug issues by including the commit hash in version information, but unfortunately, vergen is failing to build on NetBSD.

Here's the output of `cargo build`:

![image](https://user-images.githubusercontent.com/35816711/130264670-012afe0d-99e8-4f8a-bba4-b98925bb30bf.png)

EDIT: just noticed the issue isn't necessarily caused by vergen but by `git2`, should I file an issue on [git2-rs](https://github.com/rust-lang/git2-rs) instead?

**Comment by CraZySacX** [comment]
That's a problem with the `sysinfo` crate and NetBSD.   If you don't need the `sysinfo` output you can disable in your `Cargo.toml` as such:

```vergen = { version = "5.1.15", default-features = false, features = ["build","cargo","git","rustc"] }```

If you do, we will need to do something upstream with the `sysinfo` crate to ensure it works with NetBSD.

**Comment by grtcdr** [comment]
>  If you don't need the sysinfo output you can disable in your Cargo.toml as such:

Nope, we don't need sysinfo.

And specifying only those features still returns the same error.

**Comment by CraZySacX** [comment]
Ok.  Can NetBSD be run in a vm fairly easily?  I don't have access to that type of distro offhand.

**Comment by grtcdr** [comment]
Oh yes! But if you'd like to avoid going through all this trouble, I have one ready to go and can help you troubleshoot things if you'd like :)

**Comment by grtcdr** [comment]
@CraZySacX Never mind this, this whole issue could be entirely due to version incompatibility, as our runners which use Rust 1.54 cross-compile just fine but the latest Rust version on NetBSD is 1.52.

Feel free to close this :)

**Comment by 0323pin** [comment]
@CraZySacX 
Rust-1.54.0
NetBSD-current

So, I've created a GitHub account in order to have easier communication.
I still can't compile vergen crate. git2 is not an issue, it compiles just fine as a dependency of onefetch.

Here's the error,
error[E0609]: no field uid on type &Process
--> /usr/pkgsrc/wip/macchina/work/vendor/vergen-5.1.15/src/feature/si.rs:265:28
|
265 | *user.uid() == process.uid
| ^^^ unknown field

error: aborting due to previous error

For more information about this error, try rustc --explain E0609.
error: could not compile vergen

To learn more, run the command again with --verbose.
*** Error code 101

Stop.

I've also tried building it with
vergen = { version = "5.1.15", default-features = false, features = ["build","cargo","git","rustc"] } but, it still fails. I wonder why it's trying to build si even after removing the future.

**Comment by CraZySacX** [comment]
Yeah that's strange.  It does appear to be trying to compile `sysinfo` even though you have turned it off.   I'll take a look.

**Comment by 0323pin** [comment]
@CraZySacX Thanks! I don't think you need to, building 'vergen` standalone with the `si`-feature disable works fine,

```
...
===> Building for vergen-5.1.15
   Compiling libc v0.2.101
   Compiling autocfg v1.0.1
   Compiling proc-macro2 v1.0.29
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.76
   Compiling version_check v0.9.3
   Compiling pkg-config v0.3.19
   Compiling tinyvec_macros v0.1.0
   Compiling matches v0.1.9
   Compiling rustversion v1.0.5
   Compiling unicode-bidi v0.3.6
   Compiling semver v1.0.4
   Compiling log v0.4.14
   Compiling percent-encoding v2.1.0
   Compiling anyhow v1.0.44
   Compiling cfg-if v1.0.0
   Compiling bitflags v1.3.2
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling tinyvec v1.4.0
   Compiling form_urlencoded v1.0.1
   Compiling unicode-normalization v0.1.19
   Compiling jobserver v0.1.24
   Compiling time v0.1.44
   Compiling quote v1.0.9
   Compiling idna v0.2.3
   Compiling rustc_version v0.4.0
   Compiling cc v1.0.70
   Compiling url v2.2.2
   Compiling libz-sys v1.1.3
   Compiling libgit2-sys v0.12.23+1.2.0
   Compiling chrono v0.4.19
   Compiling thiserror-impl v1.0.29
   Compiling enum-iterator-derive v0.7.0
   Compiling vergen v5.1.15 (/usr/pkgsrc/wip/vergen/work/vergen-5.1.15)
   Compiling thiserror v1.0.29
   Compiling enum-iterator v0.7.0
   Compiling getset v0.1.1
   Compiling git2 v0.13.22
    Finished release [optimized] target(s) in 7m 55s
$ 
```

I suspect two different instances are calling the build and the feature needs to be disabled in both, else the wider definitions takes over.

At some point I think support should be added to `sysinfo`, unfortunately I'm not a programmer and it's a huge task to undertake. I'd be happy to help with input to `sysinfo` and NetBSD specific input but, to write the code to achive full support is over my head.

**Comment by 0323pin** [comment]
@CraZySacX Issue solved for now, see https://github.com/Macchina-CLI/libmacchina/issues/55#

Feel free to close this issue.

**Comment by jasonozias** [comment]
Closing for now.  Feel free to re-open if this continues to be an issue.
