### ISSUE TITLE
Expose the configuration to override the git repository root

### ISSUE THREAD

**Issue by Veetaha** [rustyhorde/vergen#92]
As for now the git repository anchor path (where `vergen` searches for the `.git` in parent dirs) is hardcoded to the process's current dir:
https://github.com/rustyhorde/vergen/blob/63c5da160c75413729350be8a37f9966238a5c6e/src/gen.rs#L69

According to [cargo's docs](https://doc.rust-lang.org/cargo/reference/build-scripts.html#inputs-to-the-build-script) build script's current dir is set to the source directory of the build script’s package. This leads to the inability to cleanly publish crates that use `vergen` in `build.rs` to public crates.io or private registry, since once a crate that uses `vergen`'s git feature in `build.rs` is downloaded to `~/.cargo/registry/src/.../{crate_name}-{semver_version}` directory, we are not able to compile it because there is obviously no git repository at that path.

I propose making the git repo anchor search directory configurable. As for now, we workaround this by setting the current dir of the build script to `OUT_DIR` which is heuristically ~always the subdirectory of a git repo

**Comment by jasonozias** [comment]
Yep this seems like a good idea.  I'll have time this week to work on it.

**Comment by Enter-tainer** [comment]
> As for now, we workaround this by setting the current dir of the build script to OUT_DIR which is heuristically ~always the subdirectory of a git repo

@Veetaha If someone run `cargo install your_package`, which will download source from crates.io. In this case, will `OUT_DIR` still be a subdirectory of a git repo?

**Comment by Veetaha** [comment]
@Enter-tainer unfortunately not, according to [the docs of cargo install](https://doc.rust-lang.org/cargo/commands/cargo-install.html):

> If the source is crates.io or --git then by default the crate will be built in a temporary target directory. To avoid this, the target directory can be specified by setting the CARGO_TARGET_DIR environment variable to a relative path. In particular, this can be useful for caching build artifacts on continuous integration systems.

There needs to be more sophisticated logic here for this in the build script. For example, the build script should be able to fallback to the git info of the repository where it was written. But to be able to implement that fallback that git info has to be delivered with the build script's sources, because when it is run the source repository may not be available. The easiest solution to this modifying the source of the build script before publishing the package, which isn't what `vergen` does.
