### ISSUE TITLE
Replace `chrono` with `time`?

### ISSUE THREAD

**Issue by thomaseizinger** [rustyhorde/vergen#94]
Would you accept a PR that replaces `chono` with `time`?

`chrono` seems rather unmaintained and has more dependencies than `time`, plus `time` is heavily feature-flagged.

**Comment by jasonozias** [comment]
Yeah that shouldn't be a problem.   As I recall, I only used `chrono` for formatting into UTC.

**Comment by CraZySacX** [comment]
Closing.  Feel free to open a PR with the suggested changes.
